[package]
name = "elgato_pedal_controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
regex = "1.10.3"
serde_json = "1.0"
enigo = "0.2.1"

[dependencies]
hidapi = "2.6.0"
chrono = "0.4.34"
enigo = "0.2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
home = "0.5.9"
lazy_static = "1.4.0"

[dependencies.windows-targets]
version = "0.52.4"

